document.writeln("	<footer>");
document.writeln("		<div class=\'copyright\'>");
document.writeln("			<div class=\'container\'>");
document.writeln("				<div class=\'row\'>");
document.writeln("					<div class=\'col-md-4\'>");
document.writeln("					</div>");
document.writeln("					<div class=\'col-md-5\'>");
document.writeln("						Copyright &copy; 2023. All rights reserved 从戎源码网");
document.writeln("					</div>");
document.writeln("					<div class=\'col-md-3\'>");
document.writeln("						<div class=\'pull-right\'>");
document.writeln("							<ul>");
document.writeln("								<li><img src=\'"+ctx+"/resources/images/fg/visa-curved-32px.png\' /></li>");
document.writeln("								<li><img src=\'"+ctx+"/resources/images/fg/paypal-curved-32px.png\' /></li>");
document.writeln("							</ul>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</footer>");